// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPU_JvJk8zqpzPGxHmJ_UZQKSd1PSociY',
    appId: '1:9527223797:web:36d2abfbecd7e091996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    authDomain: 'brothers-creative.firebaseapp.com',
    storageBucket: 'brothers-creative.appspot.com',
    measurementId: 'G-N8Z3TZZK5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkp3IjhXSdbH_rA7inhdYEg4WB_iLAO6I',
    appId: '1:9527223797:android:c4339f8ccb27bbf1996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    androidClientId: '9527223797-ah3l3s4u71mut4vh474fmvegjqpi773f.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_muJ8eh1Q-_6EHN_h52gbo3giZp3CEPE',
    appId: '1:9527223797:ios:7107f885508d8011996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    androidClientId: '9527223797-ah3l3s4u71mut4vh474fmvegjqpi773f.apps.googleusercontent.com',
    iosClientId: '9527223797-oonf6bhuj8tofuo4u0pn0b064t3krlsc.apps.googleusercontent.com',
    iosBundleId: 'com.brotherscreative.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_muJ8eh1Q-_6EHN_h52gbo3giZp3CEPE',
    appId: '1:9527223797:ios:7107f885508d8011996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    androidClientId: '9527223797-ah3l3s4u71mut4vh474fmvegjqpi773f.apps.googleusercontent.com',
    iosClientId: '9527223797-oonf6bhuj8tofuo4u0pn0b064t3krlsc.apps.googleusercontent.com',
    iosBundleId: 'com.brotherscreative.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt1pyQOAGEXVemERejkQs3ceM3gIxMPfo',
    appId: '1:9527223797:web:5596485739a5d7c9996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    authDomain: 'brothers-creative.firebaseapp.com',
    storageBucket: 'brothers-creative.appspot.com',
    measurementId: 'G-0JP06493FD',
  );

}